FIX ;mistakes if loop
// Code
int?[] arry = new int?[5];

// Memory view

        +-------------------+
arry --> |  Reference to Array |
        +-------------------+
                 |
                 v
        +-------------------------+
Array[0] |  null                  |
Array[1] |  null                  |
Array[2] |  null                  |
Array[3] |  null                  |
Array[4] |  null                  |
        +-------------------------+

Sum.cs(15,18): error CS0201: Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement
Sum.cs(21,22): error CS0136: A local or parameter named 'i' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
Sum.cs(15,18): error CS0165: Use of unassigned local variable 'i'

so add the for (int i ; i<n;i++) is wrong
it must be (int i =0 ; i<n ;i++)