FIX ::: mismatch in input numbers and split cant take int arguments
num.split ir right
STring.split is worng becose STRING IS a CLASS IN C SHARP

Sum.cs(12,29): error CS1061: 'int' does not contain a definition for 'Split' and no accessible extension method 'Split' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)
Sum.cs(15,32): error CS0411: The type arguments for method 'Array.ConvertAll<TInput, TOutput>(TInput[], Converter<TInput, TOutput>)' cannot be inferred from the usage. Try specifying the type arguments explicitly.

the problem is in the input i get the numbers not a string SPLIT only works for string so i must remove parse

Sum.cs(12,29): error CS1061: 'int' does not contain a definition for 'Split' and no accessible extension method 'Split' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)

new eoror:   75Leetcode   git:(main)  csc Sum.cs
Microsoft (R) Visual C# Compiler version 3.9.0-6.21124.20 (db94f4cc)
Copyright (C) Microsoft Corporation. All rights reserved.

Sum.cs(10,23): error CS0029: Cannot implicitly convert type 'string' to 'int'
Sum.cs(12,32): error CS1061: 'int' does not contain a definition for 'Split' and no accessible extension method 'Split' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)