error: no object to split
error CS0120: An object reference is required for the non-static field, method, or property 'string.Split(char, StringSplitOptions)'

this means that this:   int[] parts =string.Split(' ');  //splits the input in to parts
dose not have a aobject so must add a object