Error :missing `System.Collections.Generic'  and i added this
Valid_Parentheses.cs(13,13): error CS0246: The type or namespace name `Stack' could not be found. Are you missing `System.Collections.Generic' using directive?

2nd error
Valid_Parentheses.cs(14,13): error CS0841: A local variable `stack' cannot be used before it is declared

i fogot the capital S