FIX :::::Sum.cs(10,23): error CS0029: Cannot implicitly convert type 'string' to 'int' Sum.cs(12,32): error CS1061: 'int' does not contain a definition for 'Split' and no accessible extension method 'Split' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)
   75Leetcode   git:(main)  csc Sum.cs
Microsoft (R) Visual C# Compiler version 3.9.0-6.21124.20 (db94f4cc)
Copyright (C) Microsoft Corporation. All rights reserved.

Sum.cs(10,23): error CS0029: Cannot implicitly convert type 'string' to 'int'
Sum.cs(12,32): error CS1061: 'int' does not contain a definition for 'Split' and no accessible extension method 'Split' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)

fiest take string for the line and add them to a string arry nott mistmach dont take int and add to int arry SPLIT cant reed  ints
Sum.cs(12,32): error CS1061: 'int' does not contain a definition for 'Split' and no accessible extension method 'Split' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)

but take strings and barke them apart form the braker then convert to int using ConvortALL method
Sum.cs(10,23): error CS0029: Cannot implicitly convert type 'string' to 'int'